local LocalPlayerServiceReference,CoreGuiServiceReference=game:GetService("Players").LocalPlayer,game:GetService("CoreGui")if CoreGuiServiceReference:FindFirstChild("MobileUserInterface")or not LocalPlayerServiceReference then script:Destroy()return end
local RunServiceGameReference,MobileUserInterfaceMainContainerScreenGui,UniversalInteractionSoundEffectInstance=game:GetService("RunService"),Instance.new("ScreenGui"),Instance.new("Sound")
local RioRoleplayValidAccessKeyStringValue,RioRoleplayCurrentInputKeyStringValue,RioRoleplayKeyAlreadySavedBooleanValue,KeyStorageFileNameStringValue="X7M4P9L2K8Q1","",false,"AllScriptsLoader-Keys.txt"
local SavedKeyFileContentStringValue,SavedKeyExtractedValueStringValue="",nil if isfile and isfile(KeyStorageFileNameStringValue)then SavedKeyFileContentStringValue=readfile(KeyStorageFileNameStringValue)for SavedKeyLineIteratorStringValue in SavedKeyFileContentStringValue:gmatch("[^\r\n]+")do local SavedKeySectionNameStringValue,SavedKeyValueStringValue=SavedKeyLineIteratorStringValue:match("^(.-):%s*(.+)$")if SavedKeySectionNameStringValue=="Rio Roleplay (WithKey)"and SavedKeyValueStringValue then SavedKeyExtractedValueStringValue,RioRoleplayCurrentInputKeyStringValue,RioRoleplayKeyAlreadySavedBooleanValue=SavedKeyValueStringValue,SavedKeyValueStringValue,true end end end

UniversalInteractionSoundEffectInstance.SoundId,UniversalInteractionSoundEffectInstance.Volume="rbxassetid://139800881181209",5
MobileUserInterfaceMainContainerScreenGui.Name,MobileUserInterfaceMainContainerScreenGui.Parent,MobileUserInterfaceMainContainerScreenGui.ZIndexBehavior,MobileUserInterfaceMainContainerScreenGui.IgnoreGuiInset,MobileUserInterfaceMainContainerScreenGui.ResetOnSpawn="MobileUserInterface",CoreGuiServiceReference,Enum.ZIndexBehavior.Sibling,true,false
UniversalInteractionSoundEffectInstance.Parent=MobileUserInterfaceMainContainerScreenGui

local FluentLibraryLoadSuccessStatusBoolean,FluentLibraryMainInterfaceObjectReference=pcall(function()return loadstring(game:HttpGet("https://github.com/dawid-scripts/Fluent/releases/latest/download/main.lua"))()end)if not FluentLibraryLoadSuccessStatusBoolean or not FluentLibraryMainInterfaceObjectReference then MobileUserInterfaceMainContainerScreenGui:Destroy()script:Destroy()return end
local PrimaryDashboardMainWindowInstanceReference=FluentLibraryMainInterfaceObjectReference:CreateWindow({Title="All Script Loader",SubTitle="ByDarkszzes",TabWidth=130,Size=UDim2.fromOffset(540,320),Acrylic=false,Theme="Darker",MinimizeKey=Enum.KeyCode.LeftControl})
PrimaryDashboardMainWindowInstanceReference.Root.Position=PrimaryDashboardMainWindowInstanceReference.Root.Position-UDim2.new(0,0,0,30)

local GamesTabMainContainerSectionReference=PrimaryDashboardMainWindowInstanceReference:AddTab({Title="Games",Icon="gamepad-2"})
local RioRoleplayWithKeySystemSectionContainerReference=GamesTabMainContainerSectionReference:AddSection("Rio Roleplay (WithKey)")

RioRoleplayWithKeySystemSectionContainerReference:AddInput("RioRoleplayAccessKeyInputFieldElement",{Title="Enter Access Key",Default=SavedKeyExtractedValueStringValue or "",Placeholder="Darkszzes",Callback=function(InputValueParameter)RioRoleplayCurrentInputKeyStringValue=InputValueParameter end})
RioRoleplayWithKeySystemSectionContainerReference:AddButton({Title="Get Access Key",Callback=function()UniversalInteractionSoundEffectInstance:Play()setclipboard("https://abrir.link/wXZgp")FluentLibraryMainInterfaceObjectReference:Notify({Title="Information Panel",Content="The access key link has been copied to your clipboard. Paste it in your browser to get your key!",Duration=5})end})
RioRoleplayWithKeySystemSectionContainerReference:AddButton({Title="Execute Script Section",Callback=function()UniversalInteractionSoundEffectInstance:Play()if RioRoleplayCurrentInputKeyStringValue~=RioRoleplayValidAccessKeyStringValue then FluentLibraryMainInterfaceObjectReference:Notify({Title="Information Panel",Content="The access key you entered is invalid or incorrect. Please verify your key and try again.",Duration=5})return end FluentLibraryMainInterfaceObjectReference:Notify({Title="Information Panel",Content="Access key validated successfully! The script is now being executed.",Duration=5})loadstring(game:HttpGet("https://raw.githubusercontent.com/Darkszzes/HTML/Home/Addons/3R5B9H2J6T8N.LUA",true))()end})

local RenderSteppedConnectionForPanelVisibilityLoopReference=RunServiceGameReference.RenderStepped:Connect(function()if PrimaryDashboardMainWindowInstanceReference and PrimaryDashboardMainWindowInstanceReference.Root then PrimaryDashboardMainWindowInstanceReference.Root.Visible=true end if RioRoleplayCurrentInputKeyStringValue==RioRoleplayValidAccessKeyStringValue and not RioRoleplayKeyAlreadySavedBooleanValue then local ExistingFileContentStringValue,UpdatedFileContentStringValue,KeyFoundInFileBooleanValue="","",false if isfile and isfile(KeyStorageFileNameStringValue)then ExistingFileContentStringValue=readfile(KeyStorageFileNameStringValue)end for ExistingLineIteratorStringValue in ExistingFileContentStringValue:gmatch("[^\r\n]+")do local ExistingSectionNameStringValue=ExistingLineIteratorStringValue:match("^(.-):")if ExistingSectionNameStringValue=="Rio Roleplay (WithKey)"then UpdatedFileContentStringValue,KeyFoundInFileBooleanValue=UpdatedFileContentStringValue.."Rio Roleplay (WithKey): "..RioRoleplayCurrentInputKeyStringValue.."\n",true else UpdatedFileContentStringValue=UpdatedFileContentStringValue..ExistingLineIteratorStringValue.."\n"end end if not KeyFoundInFileBooleanValue then UpdatedFileContentStringValue=UpdatedFileContentStringValue.."Rio Roleplay (WithKey): "..RioRoleplayCurrentInputKeyStringValue.."\n"end if writefile then writefile(KeyStorageFileNameStringValue,UpdatedFileContentStringValue)end RioRoleplayKeyAlreadySavedBooleanValue=true end end)

PrimaryDashboardMainWindowInstanceReference.Root.Destroying:Connect(function()if RenderSteppedConnectionForPanelVisibilityLoopReference then RenderSteppedConnectionForPanelVisibilityLoopReference:Disconnect()RenderSteppedConnectionForPanelVisibilityLoopReference=nil end MobileUserInterfaceMainContainerScreenGui:Destroy()script:Destroy()end)
PrimaryDashboardMainWindowInstanceReference:SelectTab(1)
